version: 2.1

commands:
  setup:
    steps:
      - checkout
      - run:
          name: 'Login to npm'
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm ci

executors:
  node:
    docker:
      - image: circleci/node:14.17.4

jobs:
  lint-build:
    executor: node
    steps:
      - setup
      - run:
          name: Lint source code
          command: npm run lint
      - run:
          name: Build distribution files
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build storybook
          command: npm run build:storybook
      - run:
          name: Release pre-check
          command: npm pack
      - persist_to_workspace:
          root: .
          paths: .

  publish-release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish npm Package
          command: npm run semantic-release

workflows:
  test-and-publish:
    jobs:
      - lint-build
      - publish-release:
          filters:
            branches:
              only: master
          requires:
            - lint-build
